# Generated by Django 5.2.6 on 2025-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
