# Generated by Django 5.2.6 on 2025-09-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_body_anime_description_anime_anime_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_file',
            field=models.FileField(blank=True, null=True, upload_to='animes/'),
        ),
    ]
