# Generated by Django 5.2.1 on 2025-09-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_anime_anime_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_file',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='anime_url',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('episode_number', models.PositiveIntegerField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='episodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='app.anime')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
    ]
