# Generated by Django 5.2.1 on 2025-09-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_anime_anime_file_remove_anime_anime_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_file',
            field=models.FileField(blank=True, null=True, upload_to='animes/'),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'episode_number')},
        ),
    ]
