# Generated by Django 5.2.1 on 2025-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_anime_anime_file_anime_anime_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.CharField(blank=True, max_length=255000),
        ),
    ]
