# Generated by Django 5.2.1 on 2025-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_episode_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
