# Generated by Django 5.2.6 on 2025-09-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_season_alter_episode_unique_together_episode_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='season',
            name='description',
        ),
        migrations.RemoveField(
            model_name='season',
            name='release_year',
        ),
    ]
