# Generated by Django 5.2.6 on 2025-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_episode_anime_remove_season_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='category',
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='animes', to='app.category'),
        ),
    ]
