# Generated by Django 5.2.6 on 2025-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_episode_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.CharField(max_length=100),
        ),
    ]
