# Generated by Django 5.2.6 on 2025-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='yosh_chegara',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
