# Generated by Django 5.2.6 on 2025-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_anime_yosh_chegara_delete_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
